substitutions:
  _IMAGE: us-central1-docker.pkg.dev/careerpilot-ai-506813/careerpilot-ai/careerpilot-ai
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'careerpilot-ai'
      - '--image=${_IMAGE}'
      - '--region=us-central1'
      - '--platform=managed'
      - '--service-account=careerpilot-runtime@careerpilot-ai-506813.iam.gserviceaccount.com'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--no-allow-unauthenticated'
images:
  - '${_IMAGE}'
timeout: '600s'
options:
  logging: CLOUD_LOGGING_ONLY
