steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/careerpilot-ai
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/careerpilot-ai
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - careerpilot-ai
      - --image
      - gcr.io/$PROJECT_ID/careerpilot-ai
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --service-account
      - careerpilot-runtime@careerpilot-ai-506813.iam.gserviceaccount.com
      - --set-env-vars
      - GEMINI_MODEL=gemini-3.5-flash,GEMINI_LOCATION=asia-south1,PUBSUB_TOPIC=careerpilot-events,PUBSUB_SUBSCRIPTION=careerpilot-events-sub
images:
  - gcr.io/$PROJECT_ID/careerpilot-ai
timeout: 600s
options:
  logging: CLOUD_LOGGING_ONLY
