import type { Metadata } from "next";
import Link from "next/link";
import { AppLayout } from "@/components/layout";
import { Card, CardHeader, Badge } from "@/components/ui";
import {
  ArrowLeft,
  Code2,
  Users,
  Target,
  AlertTriangle,
  ThumbsUp,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Interview Preparation",
};

// Placeholder — will be generated by Vertex AI
const interviewPrep = {
  jobTitle: "Senior Frontend Engineer",
  company: "Google",
  technicalQuestions: [
    {
      question: "Explain the virtual DOM and how React's reconciliation algorithm works.",
      category: "React",
      difficulty: "medium" as const,
      expectedTopics: ["Virtual DOM", "Diffing algorithm", "Reconciliation", "Fiber architecture"],
      userAnswer: null,
      aiFeedback: null,
    },
    {
      question: "How would you optimize a React application that re-renders too frequently?",
      category: "Performance",
      difficulty: "hard" as const,
      expectedTopics: ["Memo", "useMemo", "useCallback", "Code splitting", "Profiler"],
      userAnswer: null,
      aiFeedback: null,
    },
    {
      question: "Describe the differences between SSR, SSG, and ISR in Next.js.",
      category: "Next.js",
      difficulty: "medium" as const,
      expectedTopics: ["Server-side rendering", "Static generation", "Incremental static regeneration", "ISR revalidation"],
      userAnswer: null,
      aiFeedback: null,
    },
    {
      question: "What is CORS and how do you handle it in a web application?",
      category: "Web",
      difficulty: "easy" as const,
      expectedTopics: ["Cross-Origin Resource Sharing", "Preflight requests", "Access-Control headers"],
      userAnswer: null,
      aiFeedback: null,
    },
  ],
  behavioralQuestions: [
    {
      question: "Tell me about a time you had to make a difficult technical decision under pressure.",
      category: "Leadership",
      difficulty: "medium" as const,
      expectedTopics: ["Decision-making", "Trade-offs", "Communication", "Outcome"],
      userAnswer: null,
      aiFeedback: null,
    },
    {
      question: "Describe a situation where you disagreed with a teammate on an architectural approach.",
      category: "Collaboration",
      difficulty: "medium" as const,
      expectedTopics: ["Conflict resolution", "Technical discussion", "Compromise", "Results"],
      userAnswer: null,
      aiFeedback: null,
    },
  ],
  roleSpecificQuestions: [
    {
      question: "How would you approach building a design system for a large engineering organization?",
      category: "Architecture",
      difficulty: "hard" as const,
      expectedTopics: ["Component API design", "Token system", "Documentation", "Adoption strategy"],
      userAnswer: null,
      aiFeedback: null,
    },
    {
      question: "How do you ensure accessibility in your frontend applications?",
      category: "Accessibility",
      difficulty: "medium" as const,
      expectedTopics: ["WCAG guidelines", "ARIA attributes", "Screen readers", "Keyboard navigation"],
      userAnswer: null,
      aiFeedback: null,
    },
  ],
  weakAreas: [
    "Web Accessibility — no direct large-scale experience",
    "Performance optimization — could use more specific examples",
  ],
  improvementSuggestions: [
    "Practice explaining React internals (virtual DOM, Fiber, reconciliation) clearly",
    "Prepare STAR-format stories for behavioral questions",
    "Review WCAG 2.1 guidelines and practice implementing them",
    "Study Google's frontend engineering blog for culture alignment",
    "Prepare questions about Google's design system approach",
  ],
};

const difficultyConfig = {
  easy: { color: "success" as const, label: "Easy" },
  medium: { color: "warning" as const, label: "Medium" },
  hard: { color: "danger" as const, label: "Hard" },
};

interface QuestionSectionProps {
  title: string;
  icon: React.ReactNode;
  questions: typeof interviewPrep.technicalQuestions;
}

function QuestionSection({ title, questions }: QuestionSectionProps) {
  return (
    <Card>
      <CardHeader
        title={title}
        subtitle={`${questions.length} questions`}
      />
      <div className="space-y-4">
        {questions.map((q, i) => {
          const diff = difficultyConfig[q.difficulty];
          return (
            <div
              key={i}
              className="rounded-lg border border-slate-100 p-4"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2">
                    <Badge variant={diff.color}>{diff.label}</Badge>
                    <Badge variant="default">{q.category}</Badge>
                  </div>
                  <p className="text-sm font-medium text-slate-900">{q.question}</p>
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {q.expectedTopics.map((topic) => (
                      <span
                        key={topic}
                        className="rounded bg-slate-50 px-2 py-0.5 text-xs text-slate-500"
                      >
                        {topic}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
              <div className="mt-3">
                <textarea
                  placeholder="Write your answer here..."
                  rows={3}
                  className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-900 placeholder:text-slate-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
                />
                <button className="mt-2 rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700">
                  Get AI Feedback
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </Card>
  );
}

export default function InterviewPrepPage() {
  return (
    <AppLayout>
      <div className="space-y-6">
        <Link
          href="/applications"
          className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700"
        >
          <ArrowLeft size={16} /> Back to Applications
        </Link>

        <div>
          <h1 className="text-2xl font-bold text-slate-900">Interview Preparation</h1>
          <p className="mt-1 text-sm text-slate-500">
            AI-generated questions and feedback for your interview with{" "}
            <span className="font-medium text-slate-700">
              {interviewPrep.company}
            </span>{" "}
            — {interviewPrep.jobTitle}
          </p>
        </div>

        {/* Weak areas & suggestions */}
        <div className="grid gap-6 lg:grid-cols-2">
          <Card className="border-l-4 border-l-yellow-400">
            <CardHeader
              title="Weak Areas"
              subtitle="Focus on these before your interview"
            />
            <ul className="space-y-2">
              {interviewPrep.weakAreas.map((area, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                  <AlertTriangle size={14} className="mt-0.5 text-yellow-500" />
                  {area}
                </li>
              ))}
            </ul>
          </Card>
          <Card className="border-l-4 border-l-green-400">
            <CardHeader
              title="Improvement Suggestions"
              subtitle="Actionable steps to prepare"
            />
            <ul className="space-y-2">
              {interviewPrep.improvementSuggestions.map((suggestion, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-slate-600">
                  <ThumbsUp size={14} className="mt-0.5 text-green-500" />
                  {suggestion}
                </li>
              ))}
            </ul>
          </Card>
        </div>

        {/* Question sections */}
        <QuestionSection
          title="Technical Questions"
          icon={<Code2 size={20} />}
          questions={interviewPrep.technicalQuestions}
        />

        <QuestionSection
          title="Behavioral Questions"
          icon={<Users size={20} />}
          questions={interviewPrep.behavioralQuestions}
        />

        <QuestionSection
          title="Role-Specific Questions"
          icon={<Target size={20} />}
          questions={interviewPrep.roleSpecificQuestions}
        />
      </div>
    </AppLayout>
  );
}
